Update cf

diff --git a/ssh/cf b/ssh/cf
--- a/ssh/cf
+++ b/ssh/cf
@@ -4,7 +4,7 @@ apt update
 apt install -y jq curl
 # Function to print error messages and exit
 function error_exit {
-    echo "Error: $1" >&2
+    echo "Error: ${1:-"Unknown Error"}" 1>&2
     exit 1
 }
 # Constants and variables
